### ISSUE TITLE
submodule example unit tests fail

### ISSUE THREAD

**Issue by nyue** [open-license-manager/examples#1]
OS : Ubuntu 18.04

nyue@head0:~/projects/Open-License-Manager/examples/build$ make test
Running tests...
Test project /home/nyue/projects/Open-License-Manager/examples/build
      Start  1: test_license
 1/12 Test  #1: test_license .....................   Passed    0.01 sec
      Start  2: test_command-line
 2/12 Test  #2: test_command-line ................   Passed    0.01 sec
      Start  3: test_project
 3/12 Test  #3: test_project .....................   Passed    0.01 sec
      Start  4: test_cryptohelper
 4/12 Test  #4: test_cryptohelper ................   Passed    0.06 sec
      Start  5: test_license_reader
 5/12 Test  #5: test_license_reader ..............***Failed    0.00 sec
      Start  6: test_os_linux
 6/12 Test  #6: test_os_linux ....................   Passed    0.00 sec
      Start  7: test_license_locator
 7/12 Test  #7: test_license_locator .............***Failed    0.00 sec
      Start  8: test_event_registry
 8/12 Test  #8: test_event_registry ..............   Passed    0.00 sec
      Start  9: test_date
 9/12 Test  #9: test_date ........................***Failed    0.01 sec
      Start 10: test_standard_license
10/12 Test #10: test_standard_license ............***Failed    0.01 sec
      Start 11: test_signature_verifier
11/12 Test #11: test_signature_verifier ..........   Passed    0.02 sec
      Start 12: test_volid
12/12 Test #12: test_volid .......................***Failed    0.13 sec

58% tests passed, 5 tests failed out of 12

Total Test time (real) =   0.29 sec

The following tests FAILED:
	  5 - test_license_reader (Failed)
	  7 - test_license_locator (Failed)
	  9 - test_date (Failed)
	 10 - test_standard_license (Failed)
	 12 - test_volid (Failed)
Errors while running CTest
Makefile:151: recipe for target 'test' failed
make: *** [test] Error 8

**Comment by gcontini** [comment]
changed src/templates/licensecc_properties_test.h.in should be ok by now.
