### ISSUE TITLE
Not building on windows

### ISSUE THREAD

**Issue by senthilsam** [open-license-manager/examples#2]
This is not building on Windows

**Comment by gcontini** [comment]
examples were broken until yesterday. Could you give them a try today? 
Remember to use Visual Studio 2017 or above and to specify -DBOOST_ROOT when you run cmake for the first time.
Install dependencies using the [windows compilation guide](http://open-license-manager.github.io/open-license-manager/development/Build-the-library-windows.html).
If the examples are still broken please reopen this issue providing more details.
